<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagementSystem_DataAccessLayer\InventoryManagementSystem_DataAccessLayer.csproj" />
    <ProjectReference Include="..\InventoryManagementSystem_Model\InventoryManagementSystem_Model.csproj" />
  </ItemGroup>

</Project>
